### PR TITLE
WIP: rewrite for stability, better usability

### PR DESCRIPTION
**Pull request by benaubin**

### CODE REVIEW

**Comment by MatthewStanciu** [comment]
Hey @benaubin, is this still happening?

**Comment by benaubin** [comment]
@MatthewStanciu  Hi Matthew. Yeah, I'm still planning on doing it, but I have no idea when I'll have the chance. If anyone else wants to take it on, they can. I probably won't have time until summer.

**Comment by MatthewStanciu** [comment]
@benaubin Sounds good. Is it cool with you if I close this PR for and you can reopen it when you get to it?

**Comment by benaubin** [comment]
@MatthewStanciu Sure thing!

**Pull request closed without merging**
